export default defineAppConfig({
  site: {
    name: 'LicenceHub',
    email: 'contact@licencehub.jp',
    domain: 'https://licencehub.jp',
    author: 'LicenceHub編集部',
    publisher: 'LicenceHub',
    ogTitle: 'LicenceHub',
    ogDescription: 'LicenceHubは、医療・資格・信頼をテーマに、登録販売者をはじめとする国家資格・通信講座をわかりやすく解説します。',
    ogUrl: 'https://licencehub.jp',
    ogType: 'website',
    ogLocale: 'ja_JP',
    ogSiteName: 'LicenceHub',
    ogImage: '/images/ogp/ogp_default.webp',
    ogImageWidth: 1200,
    ogImageHeight: 630,
    ogImageType: 'image/webp',
    ogImageAlt: 'LicenceHub',
  },
  theme: 'mistral',
  name: 'LicenseHub',
  description: 'LicenseHub is a platform for medical license navigation',
  menu: [
    { name: '受験対策', path: '/licenses/tohan/exam' },
    { name: '教材比較', path: '/licenses/tohan/materials' },
    { name: '仕事・転職', path: '/licenses/tohan/work' },
    { name: '記事一覧', path: '/licenses/tohan/articles' },
  ],
  socials: {
    github: '',
    twitter: '',
    linkedin: '',
    instagram: '',
    youtube: '',
    mastodon: '',
    bluesky: '',
    facebook: ''
  },
  // theme: 'neo-minimalist',
  logo: '/images/logo.webp',
  favicon: '/favicon.ico',
  lang: 'ja',

  robots: [
    {
      UserAgent: '*',
      Allow: ['/'],
    },
  ],
})
